[build]
  command = "npm run build"
  publish = "."

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/workbox-*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
